# Generated by Django 4.2.4 on 2023-08-23 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_likepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikePost',
        ),
    ]
