# Generated by Django 4.2.4 on 2023-08-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('technology', 'Technology'), ('animals', 'Animals'), ('automobiles', 'Automobiles'), ('humour', 'Humour'), ('nature', 'Nature'), ('news', 'News'), ('money', 'Money'), ('entertainment', 'Entertainment'), ('motivational', 'Motivational'), ('sports', 'Sports'), ('art', 'Art'), ('clips', 'Clips'), ('all', 'All')], default='all', max_length=20),
        ),
    ]
